FROM node:22 AS build

WORKDIR /build
COPY package*.json ./
COPY prisma ./prisma

RUN npm ci
COPY . .
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:22-arm64
WORKDIR ${LAMBDA_TASK_ROOT}

COPY package-lock.json package.json ./
# COPY prisma ./prisma
RUN npm ci --omit=dev
COPY . .

# Keep directory structure to ensure that the app can find Prisma client from generated path
COPY --from=build /build/prisma ./prisma
COPY --from=build /build/dist ./dist


CMD ["dist.index.handler"]
