FROM node:22 AS build
WORKDIR /build
COPY package-lock.json package.json ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate
COPY . .

FROM public.ecr.aws/lambda/nodejs:22
WORKDIR ${LAMBDA_TASK_ROOT}

COPY package-lock.json package.json ./
# COPY prisma ./prisma
RUN npm ci --omit=dev
COPY . .
COPY --from=build /build/prisma ./prisma
COPY --from=build /build/dist .




CMD ["migration-runner.handler"]